name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Checkout Clippy
      run: git clone -b rust-1.59.0 --depth 1 https://github.com/rust-lang/rust-clippy tests/clippy_workspaces/default
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy
